
#POST http://172.22.160.1:3000/signin 
#ontent-Type: application/json

#{
#    "email": "test2@thedailytech.net",
#    "password": "test1234!A"
#}

POST http://172.22.160.1:3000/signup
Content-Type: application/json

{
    "email": "test2@thedailytech.net",
    "password": "test1234!A",
    "fullname": "Test Daily Tech"
}